
tasks:
  - name: aws-cli / tree / powershell / terraform
    before: |

      # install AWS CLI
      # https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
      ./bin/aws-cli-install.sh
  
      # install tree for better visualisation of 
      # the PATH inside the terminal using command "tree"
      sudo apt-get install tree

       # isntal powershell
      # https://learn.microsoft.com/en-us/powershell/scripting/install/install-ubuntu?view=powershell-7.4
      # after powershell launch cmd "pwsh" install AWS Tools for powershell "Install-Module -Name AWS.Tools.Installer"
      # https://docs.aws.amazon.com/powershell/latest/userguide/pstools-getting-set-up-linux-mac.html
      # https://docs.aws.amazon.com/powershell/latest/reference/
      # to quit powershell type "exit"
      ./bin/powershell-install.sh
  
      # install terraform https://developer.hashicorp.com/terraform/tutorials/aws-get-started/install-cli
      ./bin/terraform-install.sh

      # install aws cdk
      # https://github.com/aws/aws-cdk
      npm i -g aws-cdk


vscode:
  extensions:
    - ms-vscode.powershell
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-pack
    - vscjava.vscode-maven
    - vscjava.vscode-java-dependency
    - ms-python.python
    - ms-python.debugpy
    - vscjava.vscode-java-test
