tasks:
  # install AWS CLI
  # https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
  - name: aws-cli and tree
    before: |
      cd /workspace 
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" 
      unzip awscliv2.zip 
      sudo ./aws/install 
      cd $THEIA_WORKSPACE_ROOT
  
  # install tree for better visualisation of 
  # the PATH inside the terminal using command "tree"
  - name: tree
    before: |
      sudo apt-get install tree

  # isntal powershell
  # https://learn.microsoft.com/en-us/powershell/scripting/install/install-ubuntu?view=powershell-7.4
  - name: powershell
    before: |
      sudo apt-get update
      sudo apt-get install -y wget apt-transport-https software-properties-common
      source /etc/os-release
      wget -q https://packages.microsoft.com/config/ubuntu/$VERSION_ID/packages-microsoft-prod.deb
      sudo dpkg -i packages-microsoft-prod.deb
      rm packages-microsoft-prod.deb
      sudo apt-get update
      sudo apt-get install -y powershell
