#!/usr/bin/env bash

# Print a message indicating the start of the bucket deletion process.
echo "== delete bucket"

# Check if a bucket name is provided as the first argument.
# If no bucket name is provided, print an error message and exit with status 1.
if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg. my-bucket-name"
    exit 1
fi

# Assign the first argument to the BUCKET_NAME variable.
BUCKET_NAME=$1

# Use the AWS CLI to delete the specified S3 bucket.
# The bucket name is specified by the BUCKET_NAME variable.
aws s3api delete-bucket \
--bucket $BUCKET_NAME 

# Print a message indicating that the bucket has been deleted.
echo "== bucket deleted"
