#!/usr/bin/env bash

# Print a message indicating the start of the object deletion process.
echo "== delete objects"

# Check if a bucket name is provided as the first argument.
# If no bucket name is provided, print an error message and exit with status 1.
if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg. my-bucket-name"
    exit 1
fi

# Check if an object key (filename) is provided as the second argument.
# If no object key is provided, print an error message and exit with status 1.
if [ -z "$2" ]; then
    echo "There needs to be a filename eg. my-bucket-name /path/to/file"
    exit 1
fi

# Assign the first argument to the BUCKET_NAME variable.
BUCKET_NAME=$1

# Assign the second argument to the OBJECT_KEY variable.
OBJECT_KEY=$2

# Use the AWS CLI to delete the specified object from the S3 bucket.
# The bucket name is specified by the BUCKET_NAME variable.
# The object key is specified by the OBJECT_KEY variable.
aws s3api delete-object \
--bucket $BUCKET_NAME \
--key $OBJECT_KEY

# Print a message indicating that the object has been deleted.
echo "== object deleted"
