#!/usr/bin/env bash
echo "== delete objects"

# Check for bucket name
if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg. my-bucket-name"
    exit 1
fi

# Check for filename
if [ -z "$2" ]; then
    echo "There needs to be a filename eg. my-bucket-name /path/to/file"
    exit 1
fi

BUCKET_NAME=$1
OBJECT_KEY=$2

aws s3api delete-object \
--bucket $BUCKET_NAME \
--key $OBJECT_KEY

echo "== object deleted"