#!/usr/bin/env bash

# Print a message indicating the start of the bucket object listing process.
echo "== list bucket"

# Check if the bucket name argument is provided.
# If not, print an error message and exit with a status code of 1.
if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg. my-bucket-name"
    exit 1
fi

# Assign the first argument to the variable BUCKET_NAME.
BUCKET_NAME=$1

# Use the AWS CLI to list objects in the specified S3 bucket.
# The `--bucket` parameter specifies the bucket from which to list objects.
aws s3api list-objects-v2 --bucket $BUCKET_NAME

# Print a message indicating the end of the bucket object listing process.
echo "== end"
